#ifndef __ECS_CONSTANTS_H__
#define __ECS_CONSTANTS_H__

#ifdef MAX_ENTITIES
#undef MAX_ENTITIES
#endif
#define MAX_ENTITIES 10000

#ifdef MAX_COMPONENT_TYPES
#undef MAX_COMPONENT_TYPES
#endif
#define MAX_COMPONENT_TYPES 32

#ifdef MAX_EVENT_TYPES
#undef MAX_EVENT_TYPES
#endif
#define MAX_EVENT_TYPES 32

#endif